name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# first need to build the rust binary in ./deploy directory
# then copy the binary to the root directory
# then run the binary
# then deploy the output to github pages
# this via gh-pages branch -D and orphan and then just copy the output to the root directory
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build
        working-directory: ./deploy

      - name: Copy binary
        run: cp ./target/debug/deploy ../deploybin
        working-directory: ./deploy

      - name: Run binary
        run: ./deploybin
      
      - name: Deploy
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          cp output/* .
          git add *.html
          git commit -m "Deploy"
          git push -f origin gh-pages
